# -*- coding: utf-8 -*-

from odoo import models, fields, api
import requests
import logging
from datetime import date

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    loopjet_generated = fields.Boolean(
        string='Generated by Loopjet',
        default=False,
        readonly=True,
        help='This quote/estimate was generated using Loopjet AI'
    )
    
    loopjet_estimate_data = fields.Text(
        string='Loopjet Estimate Data',
        readonly=True,
        help='Raw JSON data from Loopjet API response'
    )
    
    loopjet_reasoning = fields.Text(
        string='AI Reasoning',
        readonly=True,
        help='AI explanation of how this estimate was generated'
    )
    
    loopjet_estimate_id = fields.Char(
        string='Loopjet Estimate ID',
        readonly=True,
        help='UUID of this estimate in Loopjet system'
    )
    
    loopjet_synced = fields.Boolean(
        string='Synced to Loopjet',
        default=False,
        readonly=True,
        help='Whether this quotation has been synchronized to Loopjet'
    )
    
    loopjet_last_sync = fields.Datetime(
        string='Last Loopjet Sync',
        readonly=True,
        help='Last time this quotation was synced to Loopjet'
    )

    def sync_to_loopjet(self):
        """Sync this quotation/estimate to Loopjet."""
        for order in self:
            # Only sync quotations, not confirmed sales orders
            if order.state not in ['draft', 'sent']:
                continue
                
            try:
                # Get API configuration
                api_key = self.env['ir.config_parameter'].sudo().get_param('loopjet.api_key')
                if not api_key:
                    _logger.warning('Loopjet API key not configured, skipping estimate sync')
                    return
                
                api_url = 'https://loopjet-api.fly.dev'
                headers = {
                    'Authorization': f'Bearer {api_key}',
                    'Content-Type': 'application/json',
                }
                
                # Prepare estimate data
                estimate_data = {
                    'estimate_number': order.name,
                    'customer_info': {
                        'name': order.partner_id.name,
                        'email': order.partner_id.email,
                        'phone': order.partner_id.phone,
                    },
                    'issue_date': order.date_order.date().isoformat() if order.date_order else date.today().isoformat(),
                    'valid_until': order.validity_date.isoformat() if order.validity_date else None,
                    'status': 'sent' if order.state == 'sent' else 'draft',
                    'items': [],
                    'subtotal': float(order.amount_untaxed),
                    'total_tax': float(order.amount_tax),
                    'total': float(order.amount_total),
                    'external_id': str(order.id),
                    'external_system': 'odoo',
                }
                
                # Get company currency as fallback
                company_currency = self.env.company.currency_id.name if self.env.company.currency_id else 'EUR'
                
                # Add line items
                for line in order.order_line:
                    if line.product_id:
                        # Get UOM (unit of measure) - field name varies by Odoo version
                        uom_name = 'unit'
                        if hasattr(line, 'product_uom') and line.product_uom:
                            uom_name = line.product_uom.name
                        elif hasattr(line, 'product_uom_id') and line.product_uom_id:
                            uom_name = line.product_uom_id.name
                        
                        estimate_data['items'].append({
                            'name': line.product_id.name,
                            'description': line.name,
                            'quantity': line.product_uom_qty if hasattr(line, 'product_uom_qty') else line.quantity,
                            'unit_price': float(line.price_unit),
                            'unit': uom_name,
                            'currency': order.currency_id.name if order.currency_id else company_currency,
                        })
                
                # If already synced, update; otherwise create
                if order.loopjet_estimate_id:
                    url = f"{api_url}/api/v1/estimates/{order.loopjet_estimate_id}"
                    response = requests.put(url, json=estimate_data, headers=headers, timeout=30)
                else:
                    url = f"{api_url}/api/v1/estimates/"
                    response = requests.post(url, json=estimate_data, headers=headers, timeout=30)
                
                if response.status_code in [200, 201]:
                    result = response.json()
                    order.write({
                        'loopjet_estimate_id': result.get('id'),
                        'loopjet_synced': True,
                        'loopjet_last_sync': fields.Datetime.now(),
                    })
                    _logger.info(f"Successfully synced quotation {order.name} to Loopjet")
                else:
                    _logger.error(f"Failed to sync quotation {order.name}: {response.text}")
                    
            except Exception as e:
                _logger.error(f"Error syncing quotation {order.name} to Loopjet: {str(e)}")



class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    loopjet_item_id = fields.Char(
        string='Loopjet Item ID',
        readonly=True,
        help='Reference to the Loopjet estimate item'
    )

